name: foodpassport
description: Food identification and translation app for tourists.

publish_to: 'none'

version: 1.0.0+1

# FIX: Added the required SDK constraint
environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  camera: ^0.10.5
  image_picker: ^1.0.4
  google_ml_kit: ^0.20.0
  geolocator: ^11.0.0
  shared_preferences: ^2.2.2
  firebase_core: ^2.24.1
  image_picker_for_web: ^3.1.0
  sqflite: ^2.3.0
  path: ^1.8.3
  geocoding: ^2.1.1
  # FIX: Properly indented and versioned
  google_mlkit_text_recognition: ^0.15.0
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    # Add your asset paths here, for example:
    # - assets/images/
    # - assets/icons/